/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AktivitaetenRouteImport } from './routes/aktivitaeten'
import { Route as BerichtRouteImport } from './routes/bericht'
import { Route as KategorienRouteImport } from './routes/kategorien'
import { Route as NeuRouteImport } from './routes/neu'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AktivitaetenRoute = AktivitaetenRouteImport.update({
  id: '/aktivitaeten',
  path: '/aktivitaeten',
  getParentRoute: () => rootRouteImport,
} as any)
const BerichtRoute = BerichtRouteImport.update({
  id: '/bericht',
  path: '/bericht',
  getParentRoute: () => rootRouteImport,
} as any)
const KategorienRoute = KategorienRouteImport.update({
  id: '/kategorien',
  path: '/kategorien',
  getParentRoute: () => rootRouteImport,
} as any)
const NeuRoute = NeuRouteImport.update({
  id: '/neu',
  path: '/neu',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aktivitaeten': typeof AktivitaetenRoute
  '/bericht': typeof BerichtRoute
  '/kategorien': typeof KategorienRoute
  '/neu': typeof NeuRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aktivitaeten': typeof AktivitaetenRoute
  '/bericht': typeof BerichtRoute
  '/kategorien': typeof KategorienRoute
  '/neu': typeof NeuRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aktivitaeten': typeof AktivitaetenRoute
  '/bericht': typeof BerichtRoute
  '/kategorien': typeof KategorienRoute
  '/neu': typeof NeuRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/aktivitaeten' | '/bericht' | '/kategorien' | '/neu'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/aktivitaeten' | '/bericht' | '/kategorien' | '/neu'
  id: '__root__' | '/' | '/aktivitaeten' | '/bericht' | '/kategorien' | '/neu'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AktivitaetenRoute: typeof AktivitaetenRoute
  BerichtRoute: typeof BerichtRoute
  KategorienRoute: typeof KategorienRoute
  NeuRoute: typeof NeuRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aktivitaeten': {
      id: '/aktivitaeten'
      path: '/aktivitaeten'
      fullPath: '/aktivitaeten'
      preLoaderRoute: typeof AktivitaetenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bericht': {
      id: '/bericht'
      path: '/bericht'
      fullPath: '/bericht'
      preLoaderRoute: typeof BerichtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategorien': {
      id: '/kategorien'
      path: '/kategorien'
      fullPath: '/kategorien'
      preLoaderRoute: typeof KategorienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neu': {
      id: '/neu'
      path: '/neu'
      fullPath: '/neu'
      preLoaderRoute: typeof NeuRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AktivitaetenRoute: AktivitaetenRoute,
  BerichtRoute: BerichtRoute,
  KategorienRoute: KategorienRoute,
  NeuRoute: NeuRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
